app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [

  path('', views.index, name='index'),

  path('dashboard/', views.dashboard, name='dashboard'),
  path('profile/', views.profile, name='profile'),

  path('transfer/', views.transfer, name='transfer'),
  path('recharge/', views.recharge, name='recharge'),
  path('charity/', views.charity, name='charity'),

  path('transactions/', views.transactions, name='transactions'),
  path('transactionDetail/<int:pk>/', views.transactionDetail, name='transaction_detail'),
]

onlineBank/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
  # Admin site
  path('admin/', admin.site.urls),
  
  # Including apps urls
  path('app/', include('app.urls')),
  path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    # Register, Login and Logout urls
    path('register/',   views.registerUser,  name='register' ),
    path('login/',      views.loginUser,     name='login'    ),
    path('logout/',     views.logoutUser,    name='logout'   ),
]

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Load fonts from Google Font -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap" rel="stylesheet">

  <!-- Load local stylesheets -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/styles.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/all.min.css' %}">

  <!-- Set title of the page -->
  {% block title %}<title>Online Bank</title>{% endblock %}

</head>
<body class="base-container">
  
  {% block sidebar %}

    <div class="open-btn" id="sideNavOpenBtn">
      <i class="fa-solid fa-angles-down"></i>
    </div>
    <nav class="sidenav" id="sideNav">
      <div class="close-btn" id="sideNavCloseBtn">
        <i class="fa-solid fa-angles-up"></i>
      </div>
      
      {% with url_name=request.resolver_match.url_name %}
        <div class="items">
          {% if user.is_authenticated %}
            <a href="{% url 'app:dashboard' %}"
              class="{% if url_name == 'dashboard' %}active{% endif %}">dashboard
            </a>
            <a href="{% url 'app:transactions' %}"
              class="{% if url_name == 'transactions' %}active{% endif %}" >transactions
            </a>
            <a href="{% url 'app:transfer' %}"
              class="{% if url_name == 'transfer' %}active{% endif %}">transfer
            </a>
            <a href="{% url 'app:recharge' %}"
              class="{% if url_name == 'recharge' %}active{% endif %}">recharge
            </a>
            <a href="{% url 'app:charity' %}"
              class="{% if url_name == 'charity' %}active{% endif %}">charity
            </a>
            <a href="{% url 'app:profile' %}"
              class="{% if url_name == 'profile' %}active{% endif %}">profile
            </a>
            <a href="{% url 'user:logout' %}"
              class="{% if url_name == 'logout' %}active{% endif %}">logout
            </a>

          {% else %}
            <a href="{% url 'user:login' %}"
              class="{% if url_name == 'login' %}active{% endif %}">login
            </a>
            <a href="{% url 'user:register' %}"
              class="{% if url_name == 'register' %}active{% endif %}">register
            </a>
          {% endif %} 
        </div>
      {% endwith %}

      <div class="social-media">
        <i class="fa-brands fa-telegram fa-fw"></i>
        <i class="fa-brands fa-whatsapp fa-fw"></i>
        <i class="fa-brands fa-internet-explorer fa-fw"></i>
        <i class="fa-brands fa-instagram fa-fw"></i>
        <i class="fa-brands fa-linkedin fa-fw"></i>
      </div>

    </nav>
  {% endblock %}

  <!-- Header -->
  <div class="header">
    <p>Online Bank</p>
  </div>

  <main class="main-wrapper">
    {% block content %}{% endblock %}
  </main>

</body>
</html>

<script>
  // Open the sideNav
  const sideNavOpenBtn = document.querySelector("#sideNavOpenBtn");
  sideNavOpenBtn.addEventListener('click', function() {
    const sideNav = document.querySelector("#sideNav");
    sideNav.style.height = "100vh";
  })

  // Close the sideNav
  const sideNavCloseBtn = document.querySelector("#sideNavCloseBtn");
  sideNavCloseBtn.addEventListener('click', function() {
    const sideNav = document.querySelector("#sideNav");
    sideNav.style.height = "0";
  })
</script>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Load fonts from Google Font -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap" rel="stylesheet"> 

  <!-- Load local stylesheets -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/styles.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/all.min.css' %}">

  <!-- Set title of the page -->
  <title>Online Bank</title>

</head>
<body>

  <!-- Banner -->
  <div class="banner">

    <p class="title">Onlie Bank</p>

    <div class="text">

      <h2>A modern Bank in your hands.</h2>
      <h2>Join our +10,000 customers!</h2>
      <br>
      
      <p>Are you ready to start?</p>
      <form action="{% url 'user:register' %}">
        <input type="submit" value="Register" class="register-btn">
      </form>
      <form action="{% url 'user:login' %}">
        <input type="submit" value="Login" class="login-btn">
      </form>

    </div>
  </div>

  <!-- Introduction -->
  <div>
    <div class="feature-card">
      <p class="title"><i class="fa-solid fa-user-shield"></i>Secure</p>
      <p class="text">
        We take your security and privacy very seriously so that you can use our bank application without any worries.
      </p>
    </div>
    <div class="feature-card">
      <p class="title"><i class="fa-solid fa-rocket"></i>Capable</p>
      <p class="text">
        For your convenience, we have made the application fast, full-feature and reliable so that you can do most of the work online.
      </p>
    </div>
    <div class="feature-card">
      <p class="title"><i class="fa-solid fa-meteor"></i>Modern</p>
      <p class="text">
        Our designers have put all their taste and creativity to provide a user-friendly application so that you will never get lost.
      </p>
    </div>
  </div>

  <!-- Footer -->
  <div class="footer">

    <div>
      <p class="title">Contact Us:</p>
      <p><i class="fa-solid fa-envelope-open-text"></i> Email: mail@onlinebank.ir</p>
      <p><i class="fa-solid fa-building-columns"></i> Office Number: 021-24846901</p>
    </div>

    <div>
      <p class="title">Useful links:</p>
      <p><i class="fa-solid fa-link"></i> <a href="">App Tutorial</a></p>
      <p><i class="fa-solid fa-link"></i> <a href="">Terms and Conditions</a></p>
      <p><i class="fa-solid fa-link"></i> <a href="">Frequently Asked Questions</a></p>
      <p><i class="fa-solid fa-link"></i> <a href="">List of bank branches</a></p>
    </div>

    <div>
      <p class="title">Follow Us:</p>
      <div class="social-media">
        <i class="fa-brands fa-telegram fa-fw"></i>
        <i class="fa-brands fa-whatsapp fa-fw"></i>
        <i class="fa-brands fa-internet-explorer fa-fw"></i>
        <i class="fa-brands fa-instagram fa-fw"></i>
        <i class="fa-brands fa-linkedin fa-fw"></i>
      </div>
    </div>

    <p class="copy-right"><i class="fa-solid fa-copyright"></i> All Rights Reserved for Online Bank.</p>
  </div>

</body>
</html>